version: '3.8'

services:
  postgres:
    image: postgres:15-alpine
    container_name: shopdb
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: dewza1234
      POSTGRES_DB: shopdb_prod
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 10s
      timeout: 5s
      retries: 5

  app:
    build: .
    container_name: shopapp
    restart: always
    ports:
      - "3000:3000"
    environment:
      DATABASE_URL: postgresql://postgres:dewza1234@postgres:5432/shopdb_prod?schema=public
      NEXTAUTH_SECRET: my_super_secret_enterprise_key_2026_do_not_share
      NEXTAUTH_URL: http://localhost:3000
    depends_on:
      postgres:
        condition: service_healthy
    command: >
      sh -c "npx prisma db push && node server.js"

volumes:
  postgres_data:
